urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^$', 'a2a.qa.views.index'),

	(r'^question/', 'a2a.qa.views.question'),
	(r'^adv_question/', 'a2a.qa.views.adv_question'),

	(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	(r'^admin/', include(admin.site.urls)),
	(r'^accounts/', include('userena.urls')),

	(r'^tinymce/', include('tinymce.urls')),
	(r'^ajax_filtered_fields/', include('ajax_filtered_fields.urls')),
)

qa/models.py
from django import forms
from django.db import models
from django.forms import fields, widgets
from tinymce import models as tinymce_models
from userena.models import UserenaBaseProfile
from django.contrib.auth.models import User
from a2a.settings import LEVEL_SIZE

TYPE_CHOICES = (
	( 'radio', 'Single Select' ),
	( 'checkbox', 'Multiple Select' ),
)

class Question(models.Model):
	short_name = models.CharField( max_length = 20 )
	question = models.CharField( max_length = 255 )
	tip = tinymce_models.HTMLField( default = '', blank = True )
	type = models.CharField( max_length = 20, choices = TYPE_CHOICES, default = 'radio' )

	video_url = models.CharField( max_length = 255, blank = True )
	logo = models.ImageField( upload_to = 'logos', null = True, blank = True )
	badge_small = models.ImageField( upload_to = 'badges', null = True, blank = True )
	badge_large = models.ImageField( upload_to = 'badges', null = True, blank = True )

	advanced_question = models.CharField( max_length = 255, blank = True )
	advanced_tip = tinymce_models.HTMLField( default = '', blank = True )

	def __unicode__(self):
		return self.question

class Artwork(models.Model):
	title = models.CharField( max_length = 255 )
	artist = models.CharField( max_length = 255 )
	image = models.ImageField( upload_to = 'artwork/%Y/%m/%d' )
	good_questions = models.ManyToManyField( Question, verbose_name = "good questions", related_name = "good_set", blank = True )
	bad_questions = models.ManyToManyField( Question, verbose_name = "bad questions", related_name = "bad_set", blank = True )

	def __unicode__(self):
		return self.title

class ArtworkLink(models.Model):
	artwork = models.ForeignKey( Artwork )
	url = models.CharField( "URL", max_length = 255 )

	def __unicode__(self):
		return self.url

class Response(models.Model):
	question = models.ForeignKey( Question )
	response = models.CharField( max_length = 255 )
	trigger = models.BooleanField( "Triggers Advanced Question", default = True )

	def __unicode__(self):
		return self.response

class Profile(UserenaBaseProfile):
	user = models.OneToOneField( User,
		unique = True,
		verbose_name = 'user',
		related_name = 'my_profile' )

	last_seen_artwork = models.ForeignKey( Artwork, null = True, blank = True )
	last_seen_question = models.ForeignKey( Question, null = True, blank = True )

class Answer(models.Model):
	user = models.ForeignKey( User )
	artwork = models.ForeignKey( Artwork )
	question = models.ForeignKey( Question )
	responses = models.ManyToManyField( Response )
	data = models.CharField( max_length = 255, default = '' )
	hidden = models.BooleanField( "Hidden Answer", default = False )
	answered_date = models.DateTimeField( auto_now_add = True )

	def __unicode__(self):
		return u'User %s answer to %s' % ( self.user, self.artwork )

class AnswerForm( forms.ModelForm ):
	responses = forms.ModelMultipleChoiceField(
		required = True,
		queryset = Response.objects.all(),
		widget = widgets.CheckboxSelectMultiple()
	)

	class Meta:
		model = Answer
		fields = [ 'responses' ]

class Challenge(models.Model):
	short_name = models.CharField( max_length = 20 )
	question = models.CharField( max_length = 255 )
	tip = tinymce_models.HTMLField( default = '', blank = True )
	random = models.BooleanField( "Comes up randomly", default = True )

	video_url = models.CharField( max_length = 255, blank = True )
	logo = models.ImageField( upload_to = 'logos', null = True, blank = True )
	badge_small = models.ImageField( upload_to = 'badges', null = True, blank = True )
	badge_large = models.ImageField( upload_to = 'badges', null = True, blank = True )

	class Meta:
		verbose_name = 'Advanced Question'
		verbose_name_plural = 'Advanced Questions'

	def __unicode__(self):
		return self.short_name

class ChallengeAnswer(models.Model):
	user = models.ForeignKey( User )
	challenge = models.ForeignKey( Challenge )
	answer = models.ForeignKey( Answer )
	other_answer = models.ForeignKey( Answer, null = True, blank = True, related_name = 'other_answer_set' )
	response = models.TextField()
	response_date = models.DateTimeField( auto_now_add = True )

	class Meta:
		verbose_name = 'Advanced Answer'
		verbose_name_plural = 'Advanced Answers'

	def __unicode__(self):
		return u'User %s response to %s' % ( self.user, self.answer )

class AdvAnswerForm( forms.ModelForm ):
	class Meta:
		model = ChallengeAnswer
		fields = [ 'response' ]

class Level(models.Model):
	user = models.ForeignKey( User )
	question = models.ForeignKey( Question )
	adv_artwork = models.ForeignKey( Artwork, null = True, blank = True )
	answered = models.IntegerField( default = 0 )
	last_updated = models.DateTimeField( auto_now = True )

	def level(self):
		return int( self.answered / LEVEL_SIZE ) + 1

templates/adv_question.html
<div class='image'>
	<img src="{{ artwork.image.url }}"/>
	<div class='details'><span class='title'>{{ artwork.title }}</span> by <span class='artist'>{{ artwork.artist }}</span></div>
</div>

{% autoescape off %}

{% if challenge.id == 1 %}
	<h3>{{ question.advanced_question }}</h3>
	<div class="tip">{{ question.advanced_tip }}</div>
{% else %}
	<h3>{{ challenge.question }}</h3>
	<div class="tip">{{ challenge.tip }}</div>
{% endif %}

{% endautoescape %}

<form action="/adv_question/" method="POST">{% csrf_token %}
<input type="hidden" name="id_answer" value="{{ answer.id }}"/>
<input type="hidden" name="id_challenge" value="{{ challenge.id }}"/>
{% if response %}<input type="hidden" name="id_response" value="{{ response.id }}"/>{% endif %}
{% if other_answer %}<input type="hidden" name="id_other_answer" value="{{ other_answer.id }}"/>{% endif %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/index.html
<h2>Apples2Artworks</h2>

<p>A work-in-progress game for helping students learn art analysis skills.</p>

templates/profile.html
{% extends "userena/profile_detail.html" %}
{% load thumbnail %}
{% block content %}
{{ block.super }}

<h3>Levels</h3>

{% for level in profile.user.level_set.all %}
<div class="level">
	<strong>{{ level.question.short_name }}:</strong> Level {{ level.level }} ({{ level.answered }} question{{ level.answered|pluralize }} answered)
</div>
{% endfor %}

<h3>Answers</h3>

{% for answer in profile.user.answer_set.all %}
<div class="answer">
	<a href="{{ MEDIA_URL }}{{ answer.artwork.image }}"><img src="{% thumbnail answer.artwork.image 60x0 %}" style="thumb"/></a>
	<strong>{{ answer.question.question }}</strong>
	<ul>
		{% for response in answer.responses.all %}
		<li>{{ response.response }}</li>
		{% endfor %}
	</ul>
</div>
{% endfor %}

{% endblock %}

templates/question.html
<div><img src="{{ artwork.image.url }}"/></div>

{% autoescape off %}

{% if hard %}
	<h3>{{ question.advanced_question }}</h3>
	<div class="tip">{{ question.advanced_tip }}</div>
{% else %}
	<h3>{{ question.question }}</h3>
	<div class="tip">{{ question.tip }}</div>
{% endif %}

{% endautoescape %}

<form action="" method="POST">{% csrf_token %}
<input type="hidden" name="id_artwork" value="{{ artwork.id }}"/>
<input type="hidden" name="id_question" value="{{ question.id }}"/>
<input type="hidden" name="hard" value="{{ hard }}"/>
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>